version: "1.0"
info:
  model: int-scaffold
packages:
- name: TestCycleSharedProject
  gitServerName: GithubOrigin
  gitUrl: https://github.com/Munatri
  gitUsername: Munatri
  gitBranch: main
services:
- serviceName: project.testcycleshared.integrations:daf123
  packages:
  - name: TestCycleSharedProject
    version: "1.0"
- serviceName: pub.flow:debugLog
  packages:
  - name: WmPublic
    version: 12.1.0.0.1143
- serviceName: pub.math:addInts
  packages:
  - name: WmPublic
    version: 12.1.0.0.1143
